routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\AuthenticatedSessionController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\UserController;
use App\Models\Borrow;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', [AuthenticatedSessionController::class, 'index']);
Route::get('/register', [AuthenticatedSessionController::class, 'register'])->name('register.view');
Route::get('/search', [BarangController::class, 'search'])->name('search');

Route::middleware(['auth'])->resource('category', KategoriController::class);
Route::middleware(['auth'])->resource('item', BarangController::class);
Route::middleware(['auth'])->post('/item/{item}/borrow', [BarangController::class, 'borrow'])->name('item.borrow');
Route::middleware(['auth'])->resource('user', UserController::class);

Route::middleware(['auth'])->name('approval.borrow.')->prefix('/approval/borrow')->group(function () {
  Route::get('/', function () {
    return view('pages.approval.borrow')->with([
      'data' => [
        'layout' => 'layouts.web',
        'app' => 'Peminjaman',
        'page' => 'Peminjaman',
      ],
      'borrows' => Borrow::with(['user', 'item'])->where('borrow_approved', false)->get(),
    ]);
  })->name('index');

  Route::post('/{borrow}/approve', function (Borrow $borrow) {
    $borrow->update([
      'borrow_approved' => true,
      'borrowed_at' => now(),
    ]);

    return redirect()->route('approval.borrow.index')->with('success', 'Peminjaman berhasil di approve');
  })->name('approve');
});

Route::middleware(['auth'])->name('approval.return.')->prefix('/approval/return')->group(function () {
  Route::get('/', function () {
    return view('pages.approval.return')->with([
      'data' => [
        'layout' => 'layouts.web',
        'app' => 'Pengembalian',
        'page' => 'Pengembalian',
      ],
      'borrows' => Borrow::with(['user', 'item'])->where('borrow_approved', true)->where('return_approved', false)->get(),
    ]);
  })->name('index');

  Route::post('/{borrow}/approve', function (Borrow $borrow) {
    $borrow->update([
      'return_approved' => true,
      'returned_at' => now(),
    ]);

    return redirect()->route('approval.return.index')->with('success', 'Pengembalian berhasil di approve');
  })->name('approve');
});

Route::get('/peminjaman', fn () => view('pages.peminjaman.index')->with([
  'data' => [
    'layout' => 'layouts.web',
    'app' => 'Pengembalian',
    'page' => 'Pengembalian',
  ],
  'borrows' => Borrow::with(['user', 'item'])->get(),
]));

Route::get('/', [HomeController::class, 'index'])->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @var string[]
     */
    protected $with = [
        'profile',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function profile()
    {
        return $this->hasOne(Profile::class, 'user_id', 'id');
    }

    /**
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        static::created(function ($user) {
            $user->profile()->create([
                'profile_photo_url' => null,
                'age' => null,
            ]);
        });
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['layout'] = 'layouts.web';
        $data['page'] = 'User';
        $data['app'] = 'Tugas Akhir JCC Kelompok 12';

        return view('pages.user.index')->with([
            'data' => $data,
            'users' => User::where('id', '!=', 1)->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['layout'] = 'layouts.web';
        $data['page'] = 'User';
        $data['app'] = 'Tugas Akhir JCC Kelompok 12';

        return view('pages.user.create')->with('data', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:8|confirmed',
            'password_confirmation' => 'required|string|min:8|same:password',
            'role' => 'in:admin,user',
        ]);

        $user = User::create(array_merge($data, [
            'password' => Hash::make($data['password']),
        ]));

        return redirect()->route('user.index')->with('success', 'User berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $data['layout'] = 'layouts.web';
        $data['page'] = 'User';
        $data['app'] = 'Tugas Akhir JCC Kelompok 12';

        return view('pages.user.show')->with([
            'data' => $data,
            'user' => $user,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $data['layout'] = 'layouts.web';
        $data['page'] = 'User';
        $data['app'] = 'Tugas Akhir JCC Kelompok 12';

        return view('pages.user.edit')->with([
            'data' => $data,
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->update($request->validate([
            'name' => ['required', 'string', 'max:255'],
            'role' => ['in:admin,user'],
            'age' => ['integer'],
        ]));

        $user->profile->update([
            'age' => $request->age,
        ]);

        return redirect()->route('user.index')->with('success', 'User berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if ($user->delete()) {
            return redirect()->back()->with('success', 'User berhasil dihapus');
        }

        return redirect()->back()->with('error', 'User gagal dihapus');
    }
}

resources/views/pages/user/create.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <form action="{{ route('user.store') }}" method="POST">
    @csrf
    
    <div class="form-group">
      <label>Nama</label>
      <input type="text" class="form-control" name="name">
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>
    @enderror

    <div class="form-group">
      <label>Email</label>
      <input type="email" class="form-control" name="email">
    </div>

    @error('email')
      <div class="alert alert-danger">{{$message}}</div>
    @enderror

    <div class="form-group">
      <label>Kategori User</label>
      <select class="custom-select col-12">
        <option selected="">Choose...</option>
        <option value="admin">Admin</option>
        <option value="user">Peminjam</option>
      </select>
    </div>

    @error('category-user')
      <div class="alert alert-danger">{{$message}}</div>
    @enderror

    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" name="password">
    </div>

    @error('password')
      <div class="alert alert-danger">{{$message}}</div>
    @enderror

    <div class="form-group">
      <label for="exampleInputPassword1">Password Konfirmasi</label>
      <input type="password" class="form-control" name="password_confirmation">
    </div>

    @error('password_confirmation')
      <div class="alert alert-danger">{{$message}}</div>
    @enderror

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/pages/user/edit.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <form action="{{ route('user.update', $user->id) }}" method="POST">
    @csrf
    @method('put')
    <div class="form-group">
      <label>Nama User</label>
      <input type="text" class="form-control" name="name" value="{{ $user->name }}">
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>
    @enderror

    <div class="form-group">
      <label>Role</label>
      <select name="role" class="custom-select col-12">
        <option @if ($user->role == 'admin') selected @endif value="admin">Admin</option>
        <option @if ($user->role == 'user') selected @endif value="user">Peminjam</option>
      </select>
    </div>

    @error('role')
      <div class="alert alert-danger">{{$message}}</div>
    @enderror

    <div class="form-group">
      <label for="exampleInputPassword1">Umur</label>
      <input type="number" class="form-control" name="age">
    </div>

    @error('age')
      <div class="alert alert-danger">{{$message}}</div>
    @enderror

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/pages/user/index.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <div class="card-box mb-30">
    <div class="pd-20">
      <h4 class="text-blue h4">Data User</h4>
      <a href="/user/create" class="btn btn-primary">Tambah</a>
    </div>
    <div class="pb-20">
      <table class="data-table table stripe hover nowrap">
        <thead>
          <tr>
            <th class="table-plus datatable-nosort">Nama</th>
            <th>Email</th>
            <th>Active</th>
            <th>Role</th>
            <th class="datatable-nosort">Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($users as $user)
          <tr>
            <td class="table-plus">{{ mb_strtoupper($user->name) }}</td>
            <td>{{ mb_strtoupper($user->email) }}</td>
            <td>
              @if ($user->is_active === 1)
                <span class="badge bg-success">Aktif</span>
              @else
                <span class="badge bg-danger">
                  Tidak Aktif
                </span>
              @endif
            </td>
            <td>{{ mb_strtoupper($user->role) }}</td>
            <td>
              <div class="dropdown">
                <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                  <i class="dw dw-more"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                  <a class="dropdown-item" href="{{ route('user.show', $user->id) }}"><i class="dw dw-eye"></i> View</a>
                  <a class="dropdown-item" href="{{ route('user.edit', $user->id) }}"><i class="dw dw-edit2"></i> Edit</a>
                  <form action="{{ route('user.destroy', $user->id) }}" method="POST" onsubmit="event.preventDefault(); Swal.fire({
                    text: 'apakah anda yakin?',
                    icon: 'question',
                    showCancelButton: true,
                  }).then(response => response.isConfirmed && event.target.submit())">
                    @csrf
                    @method('delete')
                    <button class="dropdown-item"><i class="dw dw-delete-3"></i> Delete</button>
                  </form>
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/pages/user/show.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <div class="min-height-200px">
    <div class="page-header">
      <div class="row">
        <div class="col-md-12 col-sm-12">
          <div class="title">
            <h4>Detail User</h4>
          </div>
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Detail User</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
    <div class="blog-wrap">
      <div class="container pd-0">
        <div class="row">
          <div class="col-md-8 col-sm-12">
            <div class="blog-detail card-box overflow-hidden mb-30">
              <div class="blog-img">
                <img src="{{asset('deskapp2-master/vendors/images/img2.jpg')}}" alt="">
              </div>
              <div class="blog-caption">
                <h4 class="mb-10">Nama</h4>
                <p>{{ $user->name }}</p>
                <h4 class="mb-10">Umur</h4>
                <p>{{ $user->profile->age ?? 'Belum di tentukan' }}</p>
                <h5 class="mb-10">Email</h5>
                <p>{{ $user->email }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection