routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\AuthenticatedSessionController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\UserController;
use App\Models\Borrow;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', [AuthenticatedSessionController::class, 'index']);
Route::get('/register', [AuthenticatedSessionController::class, 'register'])->name('register.view');
Route::get('/search', [BarangController::class, 'search'])->name('search');

Route::middleware(['auth'])->resource('category', KategoriController::class);
Route::middleware(['auth'])->resource('item', BarangController::class);
Route::middleware(['auth'])->post('/item/{item}/borrow', [BarangController::class, 'borrow'])->name('item.borrow');
Route::middleware(['auth'])->resource('user', UserController::class);

Route::middleware(['auth'])->name('approval.borrow.')->prefix('/approval/borrow')->group(function () {
  Route::get('/', function () {
    return view('pages.approval.borrow')->with([
      'data' => [
        'layout' => 'layouts.web',
        'app' => 'Peminjaman',
        'page' => 'Peminjaman',
      ],
      'borrows' => Borrow::with(['user', 'item'])->where('borrow_approved', false)->get(),
    ]);
  })->name('index');

  Route::post('/{borrow}/approve', function (Borrow $borrow) {
    $borrow->update([
      'borrow_approved' => true,
      'borrowed_at' => now(),
    ]);

    return redirect()->route('approval.borrow.index')->with('success', 'Peminjaman berhasil di approve');
  })->name('approve');
});

Route::middleware(['auth'])->name('approval.return.')->prefix('/approval/return')->group(function () {
  Route::get('/', function () {
    return view('pages.approval.return')->with([
      'data' => [
        'layout' => 'layouts.web',
        'app' => 'Pengembalian',
        'page' => 'Pengembalian',
      ],
      'borrows' => Borrow::with(['user', 'item'])->where('borrow_approved', true)->where('return_approved', false)->get(),
    ]);
  })->name('index');

  Route::post('/{borrow}/approve', function (Borrow $borrow) {
    $borrow->update([
      'return_approved' => true,
      'returned_at' => now(),
    ]);

    return redirect()->route('approval.return.index')->with('success', 'Pengembalian berhasil di approve');
  })->name('approve');
});

Route::get('/peminjaman', fn () => view('pages.peminjaman.index')->with([
  'data' => [
    'layout' => 'layouts.web',
    'app' => 'Pengembalian',
    'page' => 'Pengembalian',
  ],
  'borrows' => Borrow::with(['user', 'item'])->get(),
]));

Route::get('/', [HomeController::class, 'index'])->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    /**
     * @var string[]
     */
    protected $fillable = [
        'name',
        'description',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function items()
    {
        return $this->belongsToMany(Item::class);
    }
}

resources/views/pages/category/create.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <form action="{{ route('category.store') }}" method="POST">
    @csrf
    <div class="form-group">
      <label>Nama Kategori</label>
      <input type="text" class="form-control" name="name">                
    </div>
    @error('name')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror
    <div class="form-group">
      <label for="exampleInputPassword1">Deskripsi Kategori</label>
      <textarea name="description" class="form-control"></textarea>
    </div>
    @error('description')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror           
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/pages/category/edit.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <form action="{{ route('category.update', $category->id) }}/" method="post">
    @csrf
    @method('put')
    <div class="form-group">
      <label>Nama Kategori</label>
      <input type="text" class="form-control" name="name" value="{{ $category->name }}">                
    </div>
    @error('name')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror
    <div class="form-group">
      <label for="exampleInputPassword1">Deskripsi Kategori</label>
      <textarea name="description" class="form-control">{{ $category->description }}</textarea>
    </div>
    @error('description')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror           
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/pages/category/index.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <div class="card-box mb-30">
    <div class="pd-20">
      <h4 class="text-blue h4">Data Kategori Buku</h4>
      @if(request()->user()->role == 'admin')
      <a href="/category/create" class="btn btn-primary">Tambah</a>          
      @endif
    </div>

    <div class="pb-20">
      <table class="data-table table stripe hover nowrap">
        <thead>
          <tr>
            <th class="table-plus datatable-nosort">Kategori Buku</th>
            <th>Deskripsi Buku</th>                                           
            <th class="datatable-nosort">Action</th>
          </tr>
        </thead>

        <tbody>
          @foreach($categories as $category)
          <tr>
            <td class="table-plus">{{ mb_strtoupper($category->name) }}</td>
            <td>{{ mb_strtoupper($category->description) }}</td>                    
            <td>
              <div class="dropdown">
                <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                  <i class="dw dw-more"></i>
                </a>
                
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                  <a class="dropdown-item" href="{{ route('category.show', $category->id) }}"><i class="dw dw-eye"></i> View</a>
                  @if(request()->user()->role == 'admin')
                  <a class="dropdown-item" href="{{ route('category.edit', $category->id) }}"><i class="dw dw-edit2"></i> Edit</a>
                  <form action="{{ route('category.destroy', $category->id) }}" method="post" onsubmit="event.preventDefault(); Swal.fire({
                    text: 'apakah anda yakin?',
                    icon: 'question',
                    showCancelButton: true,
                  }).then(response => response.isConfirmed && event.target.submit())">
                    @csrf
                    @method('delete')
                    <button class="dropdown-item"><i class="dw dw-delete-3"></i> Delete</button>
                  </form>
                  @endif
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/pages/category/show.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <div class="min-height-200px">
    <div class="page-header">
      <div class="row">
        <div class="col-md-12 col-sm-12">
          <div class="title">
            <h4>Detail Buku</h4>
          </div>
          <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Detail Buku</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
    <div class="blog-wrap">
      <div class="container pd-0">
        <div class="row">
          <div class="col-md-8 col-sm-12">
            <div class="blog-detail card-box overflow-hidden mb-30">
              <div class="blog-img">
                <img src="{{asset('deskapp2-master/vendors/images/img2.jpg')}}" alt="">
              </div>
              <div class="blog-caption">
                <h4 class="mb-10">Nama Kategori Buku</h4>                            
                <p>{{ $category->name }}</p>
                <h4 class="mb-10">Deskripsi</h4>
                <p>{{ $category->description }}</p>                         
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
@endsection