routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\AuthenticatedSessionController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\UserController;
use App\Models\Borrow;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', [AuthenticatedSessionController::class, 'index']);
Route::get('/register', [AuthenticatedSessionController::class, 'register'])->name('register.view');
Route::get('/search', [BarangController::class, 'search'])->name('search');

Route::middleware(['auth'])->resource('category', KategoriController::class);
Route::middleware(['auth'])->resource('item', BarangController::class);
Route::middleware(['auth'])->post('/item/{item}/borrow', [BarangController::class, 'borrow'])->name('item.borrow');
Route::middleware(['auth'])->resource('user', UserController::class);

Route::middleware(['auth'])->name('approval.borrow.')->prefix('/approval/borrow')->group(function () {
  Route::get('/', function () {
    return view('pages.approval.borrow')->with([
      'data' => [
        'layout' => 'layouts.web',
        'app' => 'Peminjaman',
        'page' => 'Peminjaman',
      ],
      'borrows' => Borrow::with(['user', 'item'])->where('borrow_approved', false)->get(),
    ]);
  })->name('index');

  Route::post('/{borrow}/approve', function (Borrow $borrow) {
    $borrow->update([
      'borrow_approved' => true,
      'borrowed_at' => now(),
    ]);

    return redirect()->route('approval.borrow.index')->with('success', 'Peminjaman berhasil di approve');
  })->name('approve');
});

Route::middleware(['auth'])->name('approval.return.')->prefix('/approval/return')->group(function () {
  Route::get('/', function () {
    return view('pages.approval.return')->with([
      'data' => [
        'layout' => 'layouts.web',
        'app' => 'Pengembalian',
        'page' => 'Pengembalian',
      ],
      'borrows' => Borrow::with(['user', 'item'])->where('borrow_approved', true)->where('return_approved', false)->get(),
    ]);
  })->name('index');

  Route::post('/{borrow}/approve', function (Borrow $borrow) {
    $borrow->update([
      'return_approved' => true,
      'returned_at' => now(),
    ]);

    return redirect()->route('approval.return.index')->with('success', 'Pengembalian berhasil di approve');
  })->name('approve');
});

Route::get('/peminjaman', fn () => view('pages.peminjaman.index')->with([
  'data' => [
    'layout' => 'layouts.web',
    'app' => 'Pengembalian',
    'page' => 'Pengembalian',
  ],
  'borrows' => Borrow::with(['user', 'item'])->get(),
]));

Route::get('/', [HomeController::class, 'index'])->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

resources/views/pages/approval/borrow.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <div class="card-box mb-30">
    <div class="pd-20">
      <h4 class="text-blue h4">Data Peminjaman Buku</h4>
    </div>

    <div class="pb-20">
      <table class="data-table table stripe hover nowrap">
        <thead>
          <tr>
            <th class="table-plus datatable-nosort">Nama Buku</th>
            <th>Peminjam</th>
            <th>Pinjam Tanggal</th>
            <th class="datatable-nosort">Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($borrows as $borrow)
          <tr>
            <td class="table-plus">{{ mb_strtoupper($borrow->item->name) }}</td>
            <td class="table-plus">{{ mb_strtoupper($borrow->user->name) }}</td>
            <td>{{ $borrow->created_at }}</td>
            <td>
              <div class="dropdown">
                <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                  <i class="dw dw-more"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                  <form action="{{ route('approval.borrow.approve', $borrow->id) }}" method="POST">
                    @csrf
                    <button class="dropdown-item"><i class="dw dw-eye"></i> Approve</button>
                  </form>
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/pages/approval/return.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <div class="card-box mb-30">
    <div class="pd-20">
      <h4 class="text-blue h4">Data Pengembalian Buku</h4>
    </div>

    <div class="pb-20">
      <table class="data-table table stripe hover nowrap">
        <thead>
          <tr>
            <th class="table-plus datatable-nosort">Nama Buku</th>
            <th>Peminjam</th>
            <th>Pinjam Tanggal</th>
            <th class="datatable-nosort">Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($borrows as $borrow)
          <tr>
            <td class="table-plus">{{ mb_strtoupper($borrow->item->name) }}</td>
            <td class="table-plus">{{ mb_strtoupper($borrow->user->name) }}</td>
            <td>{{ $borrow->created_at }}</td>
            <td>
              <div class="dropdown">
                <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                  <i class="dw dw-more"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                  <form action="{{ route('approval.return.approve', $borrow->id) }}" method="POST">
                    @csrf
                    <button class="dropdown-item"><i class="dw dw-eye"></i> Approve</button>
                  </form>
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection