routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\AuthenticatedSessionController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\UserController;
use App\Models\Borrow;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', [AuthenticatedSessionController::class, 'index']);
Route::get('/register', [AuthenticatedSessionController::class, 'register'])->name('register.view');
Route::get('/search', [BarangController::class, 'search'])->name('search');

Route::middleware(['auth'])->resource('category', KategoriController::class);
Route::middleware(['auth'])->resource('item', BarangController::class);
Route::middleware(['auth'])->post('/item/{item}/borrow', [BarangController::class, 'borrow'])->name('item.borrow');
Route::middleware(['auth'])->resource('user', UserController::class);

Route::middleware(['auth'])->name('approval.borrow.')->prefix('/approval/borrow')->group(function () {
  Route::get('/', function () {
    return view('pages.approval.borrow')->with([
      'data' => [
        'layout' => 'layouts.web',
        'app' => 'Peminjaman',
        'page' => 'Peminjaman',
      ],
      'borrows' => Borrow::with(['user', 'item'])->where('borrow_approved', false)->get(),
    ]);
  })->name('index');

  Route::post('/{borrow}/approve', function (Borrow $borrow) {
    $borrow->update([
      'borrow_approved' => true,
      'borrowed_at' => now(),
    ]);

    return redirect()->route('approval.borrow.index')->with('success', 'Peminjaman berhasil di approve');
  })->name('approve');
});

Route::middleware(['auth'])->name('approval.return.')->prefix('/approval/return')->group(function () {
  Route::get('/', function () {
    return view('pages.approval.return')->with([
      'data' => [
        'layout' => 'layouts.web',
        'app' => 'Pengembalian',
        'page' => 'Pengembalian',
      ],
      'borrows' => Borrow::with(['user', 'item'])->where('borrow_approved', true)->where('return_approved', false)->get(),
    ]);
  })->name('index');

  Route::post('/{borrow}/approve', function (Borrow $borrow) {
    $borrow->update([
      'return_approved' => true,
      'returned_at' => now(),
    ]);

    return redirect()->route('approval.return.index')->with('success', 'Pengembalian berhasil di approve');
  })->name('approve');
});

Route::get('/peminjaman', fn () => view('pages.peminjaman.index')->with([
  'data' => [
    'layout' => 'layouts.web',
    'app' => 'Pengembalian',
    'page' => 'Pengembalian',
  ],
  'borrows' => Borrow::with(['user', 'item'])->get(),
]));

Route::get('/', [HomeController::class, 'index'])->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    /**
     * @var string[]
     */
    protected $fillable = [
        'name',
        'stock',
        'floor',
    ];

    /**
     * @var string[]
     */
    protected $with = [
        'categories',
    ];

    /**
     * @var string[]
     */
    protected $withCount = [
        'borrowed',
        'returned',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function borrowed()
    {
        return $this->hasMany(Borrow::class, 'item_id', 'id')
                    ->where('borrow_approved', true)
                    ->where('return_approved', false);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function returned()
    {
        return $this->hasMany(Borrow::class, 'item_id', 'id')
                    ->where('return_approved', true);
    }
}

resources/views/pages/item/create.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <form action="{{ route('item.store') }}" method="POST">
    @csrf
    <div class="form-group">
      <label>Nama Buku</label>
      <input type="text" class="form-control" name="name">                
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror

    <div class="form-group">
      <label>Lantai</label>
      <input type="text" class="form-control" name="floor">                
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror
    
    <div class="form-group">
      <label>Total Stok</label>
      <input type="number" class="form-control" name="stock">                
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror

    <div class="form-group">
      <label>Kategori Buku</label>
      <select name="categories[]" class="custom-select col-12 multiple" multiple>
        @foreach($categories as $category)
        <option value="{{ $category->id }}">{{ mb_strtoupper($category->name) }}</option>
        @endforeach
      </select>
    </div>

    @error('categories')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/pages/item/edit.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <form action="{{ route('item.update', $item->id) }}" method="POST">
    @csrf
    @method('patch')
    <div class="form-group">
      <label>Nama Buku</label>
      <input type="text" class="form-control" name="name" value="{{ $item->name }}">
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>
    @enderror
    
    <div class="form-group">
      <label>Total Stok</label>
      <input type="number" class="form-control" name="stock" value="{{ $item->stock }}">
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror

    <div class="form-group">
      <label>Kategori Buku</label>
      <select name="categories[]" class="custom-select col-12 multiple" multiple>
        @foreach($categories as $category)
        <option value="{{ $category->id }}" @if ($item->categories->find($category->id)) selected @endif>{{ mb_strtoupper($category->name) }}</option>
        @endforeach
      </select>
    </div>

    @error('categories')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/pages/item/index.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <div class="card-box mb-30">
    <div class="pd-20">
      <h4 class="text-blue h4">Data Buku</h4> 
      @if(request()->user()->role == 'admin')
      <a href="/item/create" class="btn btn-primary">Tambah</a>
      @endif
    </div>
    
    <div class="pb-20">
      <table class="data-table table stripe hover nowrap">
        <thead>
          <tr>
            <th colspan="2" class="datatable-nosort"></th>
            <th colspan="3" class="datatable-nosort text-center">Stok</th>
            <th class="datatable-nosort"></th>
          </tr>
          <tr>
            <th class="table-plus">Nama Buku</th>
            <th>Kategori</th>
            <th>Total</th>
            <th>Dipinjam</th>
            <th>Tersedia</th>
            <th class="datatable-nosort">Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($items as $item)
          <tr>
            <td class="table-plus">{{ $item->name }}</td>
            <td>
              @foreach ($item->categories as $category)
              <span>{{ $category->name }}</span>
              @endforeach
            </td>
            <td>{{ $item->stock }}</td>
            <td>{{ $item->borrowed_count }}</td>
            <td>{{ $item->stock - $item->borrowed_count }}</td>
            <td>
              <div class="dropdown">
                <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                  <i class="dw dw-more"></i>
                </a>
                
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                  <a class="dropdown-item" href="{{ route('item.show', $item->id) }}"><i class="dw dw-eye"></i> View</a>
                  @if(request()->user()->role == 'admin')
                  <a class="dropdown-item" href="{{ route('item.edit', $item->id) }}"><i class="dw dw-edit2"></i> Edit</a>
                  <form action="{{ route('item.destroy', $item->id) }}" method="post" onsubmit="event.preventDefault(); Swal.fire({
                    text: 'apakah anda yakin?',
                    icon: 'warning',
                    showCancelButton: true,
                  }).then(response => response.isConfirmed && event.target.submit())">
                    @csrf
                    @method('delete')
                    <button class="dropdown-item"><i class="dw dw-delete-3"></i> Delete</button>
                  </form>
                  @endif

                  @if (request()->user()->is_active === 1)
                    <form action="{{ route('item.borrow', $item->id) }}" method="POST">
                      @csrf
                      <button type="submit" class="dropdown-item"><i class="dw dw-cart"></i> Pinjam</button>
                    </form>
                  @endif
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/pages/item/search.blade.php
<!DOCTYPE html>
<html>
<head>
	<!-- Basic Page Info -->
	<meta charset="utf-8">
	<title>@yield('title')</title>

	<!-- Site favicon -->
	<link rel="apple-touch-icon" sizes="180x180" href="{{asset('deskapp2-master/vendors/images/apple-touch-icon.png')}}">
	<link rel="icon" type="image/png" sizes="32x32" href="{{asset('deskapp2-master/vendors/images/favicon-32x32.png')}}">
	<link rel="icon" type="image/png" sizes="16x16" href="{{asset('deskapp2-master/vendors/images/favicon-16x16.png')}}">

	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
	<!-- CSS -->
	<link rel="stylesheet" type="text/css" href="{{asset('deskapp2-master/vendors/styles/core.css')}}">
	<link rel="stylesheet" type="text/css" href="{{asset('deskapp2-master/vendors/styles/icon-font.min.css')}}">
	<link rel="stylesheet" type="text/css" href="{{asset('deskapp2-master/src/plugins/datatables/css/dataTables.bootstrap4.min.css')}}">
	<link rel="stylesheet" type="text/css" href="{{asset('deskapp2-master/src/plugins/datatables/css/responsive.bootstrap4.min.css')}}">
	<link rel="stylesheet" type="text/css" href="{{asset('deskapp2-master/vendors/styles/style.css')}}">

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
	<script src="{{ asset('/js/sweetalert2.min.js') }}" defer></script>
	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" defer></script>
	<script>
		document.addEventListener('DOMContentLoaded', function() {
			const Toast = Swal.mixin({
				toast: true,
				position: 'top-end',
				showConfirmButton: false,
				timer: 3000
			});

			@if(session('success'))
				Toast.fire({
					icon: 'success',
					title: '{{ session('success') }}'
				})
			@endif

			@if(session('error'))
				Toast.fire({
					icon: 'error',
					title: '{{ session('error') }}'
				})
			@endif

			$('.multiple').select2();
		});
	</script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-119386393-1');
	</script>
</head>
<body>
	<div class="pre-loader">
		<div class="pre-loader-box">
			<div class="loader-logo"><img src="{{asset('deskapp2-master/vendors/images/deskapp-logo.svg')}}" alt=""></div>
			<div class='loader-progress' id="progress_div">
				<div class='bar' id='bar1'></div>
			</div>
			<div class='percent' id='percent1'>0%</div>
			<div class="loading-text">
				Loading...
			</div>
		</div>
	</div>


	<div class="right-sidebar">
		<div class="sidebar-title">
			<h3 class="weight-600 font-16 text-blue">
				Layout Settings
				<span class="btn-block font-weight-400 font-12">User Interface Settings</span>
			</h3>
			<div class="close-sidebar" data-toggle="right-sidebar-close">
				<i class="icon-copy ion-close-round"></i>
			</div>
		</div>
		<div class="right-sidebar-body customscroll">
			<div class="right-sidebar-body-content">
				<h4 class="weight-600 font-18 pb-10">Header Background</h4>
				<div class="sidebar-btn-group pb-30 mb-10">
					<a href="javascript:void(0);" class="btn btn-outline-primary header-white active">White</a>
					<a href="javascript:void(0);" class="btn btn-outline-primary header-dark">Dark</a>
				</div>

				<h4 class="weight-600 font-18 pb-10">Sidebar Background</h4>
				<div class="sidebar-btn-group pb-30 mb-10">
					<a href="javascript:void(0);" class="btn btn-outline-primary sidebar-light ">White</a>
					<a href="javascript:void(0);" class="btn btn-outline-primary sidebar-dark active">Dark</a>
				</div>

				<h4 class="weight-600 font-18 pb-10">Menu Dropdown Icon</h4>
				<div class="sidebar-radio-group pb-10 mb-10">
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" id="sidebaricon-1" name="menu-dropdown-icon" class="custom-control-input" value="icon-style-1" checked="">
						<label class="custom-control-label" for="sidebaricon-1"><i class="fa fa-angle-down"></i></label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" id="sidebaricon-2" name="menu-dropdown-icon" class="custom-control-input" value="icon-style-2">
						<label class="custom-control-label" for="sidebaricon-2"><i class="ion-plus-round"></i></label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" id="sidebaricon-3" name="menu-dropdown-icon" class="custom-control-input" value="icon-style-3">
						<label class="custom-control-label" for="sidebaricon-3"><i class="fa fa-angle-double-right"></i></label>
					</div>
				</div>

				<h4 class="weight-600 font-18 pb-10">Menu List Icon</h4>
				<div class="sidebar-radio-group pb-30 mb-10">
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" id="sidebariconlist-1" name="menu-list-icon" class="custom-control-input" value="icon-list-style-1" checked="">
						<label class="custom-control-label" for="sidebariconlist-1"><i class="ion-minus-round"></i></label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" id="sidebariconlist-2" name="menu-list-icon" class="custom-control-input" value="icon-list-style-2">
						<label class="custom-control-label" for="sidebariconlist-2"><i class="fa fa-circle-o" aria-hidden="true"></i></label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" id="sidebariconlist-3" name="menu-list-icon" class="custom-control-input" value="icon-list-style-3">
						<label class="custom-control-label" for="sidebariconlist-3"><i class="dw dw-check"></i></label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" id="sidebariconlist-4" name="menu-list-icon" class="custom-control-input" value="icon-list-style-4" checked="">
						<label class="custom-control-label" for="sidebariconlist-4"><i class="icon-copy dw dw-next-2"></i></label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" id="sidebariconlist-5" name="menu-list-icon" class="custom-control-input" value="icon-list-style-5">
						<label class="custom-control-label" for="sidebariconlist-5"><i class="dw dw-fast-forward-1"></i></label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" id="sidebariconlist-6" name="menu-list-icon" class="custom-control-input" value="icon-list-style-6">
						<label class="custom-control-label" for="sidebariconlist-6"><i class="dw dw-next"></i></label>
					</div>
				</div>

				<div class="reset-options pt-30 text-center">
					<button class="btn btn-danger" id="reset-settings">Reset Settings</button>
				</div>
			</div>
		</div>
	</div>

	<div class="">
		<div class="pd-ltr-20">
            <div class="card-box mb-30">
                <div class="pd-20">
                <h4 class="text-blue h4">Data Buku</h4> 
                <a href="/login" class="btn btn-primary">Login</a>          
                </div>
                
                <div class="pb-20">
                <table class="data-table table stripe hover nowrap">
                    <thead>
                    <tr>
                        <th colspan="2" class="datatable-nosort"></th>
                        <th colspan="3" class="datatable-nosort text-center">Stok</th>
                        <th class="datatable-nosort"></th>
                    </tr>
                    <tr>
                        <th class="table-plus">Nama Buku</th>
                        <th>Kategori</th>
                        <th>Total</th>
                        <th>Dipinjam</th>
                        <th>Tersedia</th>
                        <th class="datatable-nosort">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($items as $item)
                    <tr>
                        <td class="table-plus">{{ $item->name }}</td>
                        <td>
                        @foreach ($item->categories as $category)
                        <span>{{ $category->name }}</span>
                        @endforeach
                        </td>
                        <td>{{ $item->stock }}</td>
                        <td>{{ $item->borrowed_count }}</td>
                        <td>{{ $item->stock - $item->borrowed_count }}</td>
                        <td>
                        <div class="dropdown">
                            <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                            <i class="dw dw-more"></i>
                            </a>
                            
                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                            <a class="dropdown-item" href="{{ route('item.show', $item->id) }}"><i class="dw dw-eye"></i> View</a>
                            </div>
                        </div>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
                </div>
            </div>
        </div>
	</div>
	<!-- js -->
	<script src="{{asset('deskapp2-master/vendors/scripts/core.js')}}"></script>
	<script src="{{asset('deskapp2-master/vendors/scripts/script.min.js')}}"></script>
	<script src="{{asset('deskapp2-master/vendors/scripts/process.js')}}"></script>
	<script src="{{asset('deskapp2-master/vendors/scripts/layout-settings.js')}}"></script>
	<!-- <script src="{{asset('deskapp2-master/src/plugins/apexcharts/apexcharts.min.js')}}"></script> -->
    <script src="{{asset('deskapp2-master/src/plugins/datatables/js/jquery.dataTables.min.js')}}"></script>
	<script src="{{asset('deskapp2-master/src/plugins/datatables/js/dataTables.bootstrap4.min.js')}}"></script>
	<script src="{{asset('deskapp2-master/src/plugins/datatables/js/dataTables.responsive.min.js')}}"></script>
	<script src="{{asset('deskapp2-master/src/plugins/datatables/js/responsive.bootstrap4.min.js')}}"></script>
	<!-- <script src="{{asset('deskapp2-master/vendors/scripts/dashboard.js')}}"></script> -->
    <!-- buttons for Export datatable -->
	<script src="{{asset('deskapp2-master/src/plugins/datatables/js/dataTables.buttons.min.js')}}"></script>
	<script src="{{asset('deskapp2-master/src/plugins/datatables/js/buttons.bootstrap4.min.js')}}"></script>
	<script src="{{asset('deskapp2-master/src/plugins/datatables/js/buttons.print.min.js')}}"></script>
	<script src="{{asset('deskapp2-master/src/plugins/datatables/js/buttons.html5.min.js')}}"></script>
	<script src="{{asset('deskapp2-master/src/plugins/datatables/js/buttons.flash.min.js')}}"></script>
	<script src="{{asset('deskapp2-master/src/plugins/datatables/js/pdfmake.min.js')}}"></script>
	<script src="{{asset('deskapp2-master/src/plugins/datatables/js/vfs_fonts.js')}}"></script>
	<!-- Datatable Setting js -->
	<script src="{{asset('deskapp2-master/vendors/scripts/datatable-setting.js')}}"></script>
</body>
</html>

resources/views/pages/item/show.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')

<div class="min-height-200px">
  <div class="page-header">
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <div class="title">
          <h4>Detail Buku</h4>
        </div>
        <nav aria-label="breadcrumb" role="navigation">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Detail Buku</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
  <div class="blog-wrap">
    <div class="container pd-0">
      <div class="row">
        <div class="col-md-8 col-sm-12">
          <div class="blog-detail card-box overflow-hidden mb-30">
            <div class="blog-img">
              <img src="{{asset('deskapp2-master/vendors/images/img2.jpg')}}" alt="">
            </div>

            <div class="blog-caption">
              <h4 class="mb-10">Nama Buku</h4>
              <p>{{ $item->name }}</p>
              <h4 class="mb-10">Kategori Buku</h4>
              <p>
                @foreach ($item->categories as $category)
                <span>{{ $category->name }}</span>
                @endforeach
              </p>
              <h4 class="mb-10">Total Stok</h4>
              <p>{{ $item->stock }}</p>
              <h4 class="mb-10">Stok Tersedia</h4>
              <p>{{ $item->stock - $item->borrowed_count }}</p>
              <h4 class="mb-10">Stok Dipinjam</h4>
              <p>{{ $item->borrowed_count }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection